version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: raw data from Greenweez
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez/ we have one row per product_id found ineach order_id
      - name: product
        identifier: raw_gz_product
        tests:
          - unique:
              column_name:"(purchase_price || '-' || product_id)"
        description: purchase_price and product_id
      - name: ship
        identifier: raw_gz_ship
        description: 4 columns with the order_id, the shipping_fee, logcost and ship_cost
