version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: raw data from Greenweez
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez/ we have one row per product_id found in each order_id
        tests:
          - unique:
              column_name: "(pdt_id || '-' || orders_id)"

      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null

      - name: ship
        identifier: raw_gz_ship
        description: 4 columns with the order_id, the shipping_fee, logcost and ship_cost
        columns:
          - name : orders_id
            description : primary key of the table 
            tests: 
                - unique
                - not_null

